fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    

app_user:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /

app_cart:
    resource: "@AppCartBundle/Resources/config/routing.yml"
    prefix:   /

app_layout:
    resource: "@AppLayoutBundle/Resources/config/routing.yml"
    prefix:   /

app_product:
    resource: "@AppProductBundle/Resources/config/routing.yml"
    prefix:   /

