product_list:
    path:     /
    defaults: { _controller: AppProductBundle:Product:index }

product_new:
    path:     /product/new
    defaults: { _controller: AppProductBundle:Product:new }

product_delete:
    path:     /product/delete/{id}
    defaults: { _controller: AppProductBundle:Product:delete }

product_edit:
    path:     /product/edit/{id}
    defaults: { _controller: AppProductBundle:Product:edit }

AppProductBundle_category:
        resource: "@AppProductBundle/Resources/config/routing/category.yml"
        prefix:   /category
